Added all Harry Potter Movies to data.json
brittanyrw/emojiscreen pull request #92
Opened 2019-08-13 14:24 UTC by harsukhdeol

- [ ] 🔍 I have searched the `data.json` file and confirmed I am not adding a duplicate entry.
- [ ] 🌈 I have added a single year under `date`. Note: Do not add ranges such as 2017-2019. 
- [ ] 📅 I have added a type from one of the following: `movie` , `tv` or `musical`.
- [ ] 3️⃣ I have at least three emojis listed under `emojiImgs` and 5️⃣ less than five emojis listed under `emojiImgs`.
- [ ] 👍 My pull request has a descriptive title (such as `Added The Lion King` or `Added Black Panther, The Avengers: Endgame and Thor`)
- [ ] ⭐ My genres are all inside of square brackets `[ ]` and each are individually wrapped in quotation marks and have a comma between each one. (such as submitting this `"genres": ["adventure","mystery","animation"]` and not this `"genres":["adventure, mystery, animation"]`)
- [ ] 🖍️ I have placed the new show(s) or movie(s) in alphabetical order based on title. 

👋 If this pull request closes an issue, replace the --- with the issue number.

Closes #---

2019-08-13 14:56 UTC, brittanyrw requested changes
Hi, it looks like some of your movie additions have more than five emojis. Please update your code so that each entry has a maximum of five emojis. Thanks!

2019-08-14 02:34 UTC, harsukhdeol commented
Thanks for pointing that out. I guess I missed some, it should be good now.

2019-08-14 17:13 UTC, brittanyrw approved these changes

2019-08-14 17:14 UTC, brittanyrw commented
@harsukhdeol Looks great! I will accept this and you should be able to see the movies you added at emojiscreen.com within the next few minutes.

2019-08-14 17:14 UTC, merged